name: 
  bones
description: 
  A minimalist text-only browser built with Flutter
version: 
  1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  http: ^1.1.0
  html: ^0.15.4
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  golden_toolkit: ^0.15.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/app_logo.png
  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/Times_New_Roman.ttf
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Regular.ttf

flutter_icons:
  android: true
  ios: false
  image_path: assets/app_logo.png